global:
  scrape_interval: 15s # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules

scrape_configs:
  - job_name: 'match_app' # Name for this scrape job
    metrics_path: /actuator/prometheus
    scheme: http

    static_configs:
      - targets: ['localhost:8080'] # Replace with your app's host and port