global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'match-app'
    metrics_path: '/actuator/prometheus' # As configured in application.properties
    static_configs:
      - targets: ['match-app:8080'] # Docker Compose service name and port for the app